# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0dad6edbddaea8308bcc8ff1dacdc13b433b67ed430f1780c8ef0cc3e70b723c89b8e1dc96496d2273062b4f2574ebe61141f446c7368792f2caf66755c48d

test:
  secret_key_base: d591d7127debd281da615194aab692cfda4269fc03dab33abd15512181e99ca0815651edbfbbc3be0825cbe8b00cd9e61809f79ad7ac156a46e85273c18f2cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
